---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith
spec:
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
      - name: monolith
        image: pangliter/monolith-java-jib-f3
        env:
          - name: NOTIFICATION_HOST
            value: notification:8080
          - name: NOTIFICATION_SERVICE_MICROSERVICES
            value: true
---
apiVersion: v1
kind: Service
metadata:
  name: monolith
  labels:
    app: monolith
spec:
  ports:
    - port: 8080
  selector:
    app: monolith
  type: NodePort